name: deploy

on:
  push:
    branches:
    - main
  schedule:
    - cron: "0 0 */7 * *"

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 14
    
    - name: Build JSON
      run: ./build_json_in_docker.sh
    
    - name: Install dependencies
      run: npm install
    
    - name: Build website
      run: npm run build

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist/
